### ISSUE TITLE
TypeScript Typings, again

### ISSUE THREAD

**Issue by atrauzzi** [solkimicreb/react-easy-state#12]
Issue #4 was mistakenly closed due to a misunderstanding as to what "TypeScript support" implies.

It isn't that special steps are required to use this library with TypeScript and/or WebPack. That's unrelated to what #4 was implying.

The request came about because there are no typings available so when you use this library with TypeScript, no hinting is available.  This is also an issue when you have no implicit any enabled as that prevents you from importing the library.

Most TypeScript projects will have [no implicit any](https://www.typescriptlang.org/docs/handbook/compiler-options.html) enabled as that's largely the whole point of TypeScript -- to avoid having untyped references in your code!

Anyway -- what would be great is if this project's author created a `.d.ts` file and added it to this repository. The `.d.ts` file is [kind of like a c header file that contains the definition of the signatures](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) of any types exported by this library.

Again, issue #4 was closed in error based on a misunderstanding of both TypeScript and its ecosystem.

**Comment by solkimicreb** [comment]
I got it now 🙂 Thanks for not giving up on this. Types are on the way!

**Comment by atrauzzi** [comment]
Awesome!

**Comment by solkimicreb** [comment]
Initial PR is here: https://github.com/solkimicreb/react-easy-state/pull/13. It works, but it can be improved. I will polish it a bit more with imported types from @types/react and publish it with v4.1.0 tomorrow at latest. Going to sleep now 🙂

**Comment by atrauzzi** [comment]
Added a quick suggestion. 😄

**Comment by solkimicreb** [comment]
Improved it a bit: https://github.com/solkimicreb/react-easy-state/pull/13 Could you take a look again?

**Comment by atrauzzi** [comment]
Looks good! 😄

**Comment by solkimicreb** [comment]
v4.1.0 is out on npm with the type definitions. I am closing this now, but feel free to reopen it if you have issues with it (I am still not a TypeScript master 😄 )

Thanks for the issue 🙂

**Comment by atrauzzi** [comment]
No problem, I think you've got the gist of it.  Really, having the typings at all in the repo is half the battle.

Thank you very much!

**Comment by solkimicreb** [comment]
@atrauzzi I am really sorry 😞 It turned out that I forgot to publish the TypeScript type definitions on npm (it was not added to the whitelisted files). It should finally work now with [v4.1.1](https://github.com/solkimicreb/react-easy-state/releases/tag/v4.1.1).

**Comment by atrauzzi** [comment]
No problem! I'm going to be trying this library out in my next project(s), so you haven't hurt my timeline at all.  Really looking forward to the simplicity (vs redux) this library and async support in react offers!
