### ISSUE TITLE
Using this.setState doesn't trigger a re-render. Intentional?

### ISSUE THREAD

**Issue by slavabez** [solkimicreb/react-easy-state#19]
Hi! Awesome library, trying to use it in my project now and realised that using the 'vanilla' component state doesn't seem to work. Is that intended, do I simply use a local store for my component for the same functionality?

if it's intended, perhaps it's worth including that component state shouldn't be used more explicitly in the docs (for people like me)?

**Comment by solkimicreb** [comment]
This was not intended, I already fixed and tested it and it will be included in the next release. I would prefer local stores over react state, but Easy State should not mess with vanilla React behavior.

Thanks for the catch (: I am leaving the issue open until I put the release on npm

**Comment by solkimicreb** [comment]
Fixed and released with v4.1.2 https://github.com/solkimicreb/react-easy-state/releases/tag/v4.1.2
