### ISSUE TITLE
Middlewares support

### ISSUE THREAD

**Issue by yuraxdrumz** [solkimicreb/react-easy-state#26]
Hey.
I really like react-easy-state, it is easy enough to work with, simple, clean and not messy like redux or mobx.
One thing i really liked about redux is the fact you can pass middlewares, for example I can pass an error-logger middleware which logs all new state changes and in case of an error in the users browser i take a snapshot of all the stores, the input and operations the user did and try to recreate it to fix the bugs.
Are there plans for adding middlewares in the future or should I just wrap all my stores and call one function that does what I need instead ? 

```
const { store }  = 'react-easy-state'

const UserStore = store({
    name:'',
    lastName:''
})

const OtherStore = store({
    otherName:'',
    otherLastName:'',
    updateUserName:function(name){
        console.log('updating with name', name)
        OtherStore.name = name
    }
})

const loggerMiddleware = (...args) => {
    console.log(`this is logger middleware`, args)
}

const otherMiddleware = (...args) => {
    console.log(`this is other middleware`, args)
}

// if array, map on it, if object get keys and map on it
const map = (toIterateOver,func) => {
    return Array.isArray(toIterateOver) ? 
        toIterateOver.map(func) : 
        typeof toIterateOver === 'object' ? 
        Object.keys(toIterateOver).map(func) : 
        void(0)
}

// apply middleware func
const applyMiddleware = (middlewares, store, prop)=>{
    // copy old function
    const oldFunc = store[prop].bind(null)
    // overwrite function to apply middlewares, then, call original function with original args
    store[prop] = async function (...args){
        console.log(arguments)
        for(let middleware of middlewares){
            await middleware(...args)
        }
        oldFunc.call(null, ...args)
    }
}

// pass middlewares and stores
const createStores = helperMapFunc => (...middlewares) => (...stores) => {
    // map on stores
    helperMapFunc(stores, storeObject=>{
        // map on store props
        helperMapFunc(storeObject, prop=>{
            // if store has own prop and it is func apply middlewares
            storeObject.hasOwnProperty(prop) && typeof storeObject[prop] === 'function' && applyMiddleware(middlewares, storeObject, prop)         
        })
    })
    // return stores for usage
    return {
        ...stores
    }
}

export default createStores(map)(loggerMiddleware, otherMiddleware)(UserStore, OtherStore)
```

**Comment by solkimicreb** [comment]
Do you have any other use case for middlewares apart from devtools? I devtool is already in the making (I am super slow with it because of my other projects). It will have proper timetravel, logging, session replay support - like Redux.

Easy State v5 is already prepared for a devtool, it just needs a filtering and displaying component. You can test out the raw data stream with `view(Comp, { devtool: console.log })`. In this case `console.log` plays the role of a very primitive devtool.

**Comment by yuraxdrumz** [comment]
Good to know, I added an example of something simple with applying middlewares, but sure, I will try the devtool, thanks and keep up the good work man!

**Comment by walidvb** [comment]
Hey, using react easy state for the first time here, and am indeed finding it easy.

I have a project which is offline-capable, and needs to persist state between sessions. A middleware to bind to localStorage would be nice :)
Thanks @yuraxdrumz for the code, i'll take a look

**Comment by solkimicreb** [comment]
@walidvb You don't need middlewares for that. Easy state is a thin wrapper around the [observer-util](https://github.com/nx-js/observer-util) which can be used to create more general reactions (not just for React components). This one synchronizes a store with localStorage on every change of it.

```js
import { store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const myStore = store(JSON.parse(localStorage.getItem('MY_STORE')))

observe(() => {
  localStorage.setItem('MY_STORE', JSON.stringify(myStore))
})
```

**Comment by walidvb** [comment]
great to know that, thanks!

**Comment by walidvb** [comment]
I think it is worth mentioning your [other library](https://github.com/solkimicreb/react-easy-params), which does this, as well as handle params: 
(also mentioned in #39)

PS: still need to check how your `localStorageKey` there isn't overridden in case of multiple storages, but haven't really taken a look yet :) 

In any case, you're making a huge game changer!!
