### ISSUE TITLE
Modules and actions

### ISSUE THREAD

**Issue by andyjessop** [solkimicreb/react-easy-state#29]
Lovely little library, nicely done.

I have just a few questions about how I might integrate it into a decently-sized app. It would be good to see examples of how these things might be done:

1. Vuex has the concept of modules, where you can keep functionality modular, but also communicate between modules (via `root`) to wire an app together. I'm wondering how this might be done in `react-easy-state` -an example of an app with multiple stores to explain this more clearly would be great.

2. The actions seem a bit cumbersome, having to reference the store by name seems to mean that you can't define actions separately and then include them in a "config" that creates a store. So I'm wondering if a store basically needs to be a huge file with all actions inside. This kind of separation would be most welcome.

**Comment by solkimicreb** [comment]
Hi!

I will add some bigger examples soon, until then here are your answers 🙂 

1. I would just have multiple stores and use simple ES6 import/export, React props or React context to pass them around. I left out DI purposefully from the library, I think that people tend to overcomplicate it. You can really mix things however you want, there are no restrictions. You can import a store in another store's file and modify it from the other store's methods or use getters to proxy to the other store - as examples.

2. There are no actions in Easy State. You can mutate the store however you want to - from inside our outside the store. I feel like people naturally assume restrictions here, but there are none. Check my [Stress Testing Easy State article](https://medium.com/@solkimicreb/stress-testing-react-easy-state-ac321fa3becf) to see some examples of mutating stores directly from the console.
