### ISSUE TITLE
Seeing some odd issues after updating to 5.0.0 from 4.1.2

### ISSUE THREAD

**Issue by bleeinc** [solkimicreb/react-easy-state#31]
I know auto-bind was removed but did this change how stores behave? I wrote my own auto-bind once I saw that it was going to be removed but my stores appear to have some issues after the update. Read the release notes and it didn't mention any particular changes to stores but I see that the 'store.js' file is now gone and is now just exporting a plain observable. I think this may be a breaking change.

**Comment by bleeinc** [comment]
I think the issue was that i didn't realize all components using the view HOC were getting autoBound and when I switched to my autoBind it stopped working -__- gotta go and ensure everything explicitly uses my autoBinder.

**Comment by solkimicreb** [comment]
Yeah, the only breaking change was the removal of auto-bind. The `store.js` file only added the auto-bind to the observables (so I could completely remove it).
