### ISSUE TITLE
How to connect two stores

### ISSUE THREAD

**Issue by kiwi1342** [solkimicreb/react-easy-state#33]
Hi, 

I'm trying to connect two stores which live in separated files, but changing the value on one, is not reflected on the other.

You can see an example here:

https://codesandbox.io/s/z6055yr7kp

I'm simulating an ajax request with the setTimeout and, you can see in the codesandbox console, when changing the `role` from 'user' to 'admin' in the userStore.js, the `isLoading` function from the store.js is called but the `role` value is not intercepted.

I'm not sure if this is a bug or just me making a stupid mistake.

ps.
thanks for this project! Is amazing!

**Comment by solkimicreb** [comment]
Hi,

I am not 100% sure I understand the issue. Would you like to bind two values from two stores together in the following way?

```js
import { store } from 'react-easy-state'

const store1 = store({ value: 'x' })
const store2 = store({ value: store1.value })

// this also sets store2.value to 'Hello'
store1.value = 'Hello'

// this logs hello
console.log(store2.value)
```

This is possible with the [underlying reactivity library](https://github.com/nx-js/observer-util) in the following way

```
import { observe } from '@nx-js/observer-util'
import { store } from 'react-easy-state'

const store1 = store({ value: 'x' })
const store2 = store({})

observe(() => store2.value = store1.value)

// this triggers the above observed function, which sets store2.value to store1.value
store1.value = 'Hello'
// this logs hello
console.log(store2.value)
```

I would advise against doing this though. Reactivity is best used to reflect the state in the view - which is done by Easy State without added hustle, as it was designed for this. The view is a display for the user and you do not pull data from it (except for user events). You can think of it as the final destination of your data. Updating other data with reactive data can lead to messy chains and unmaintainable code, it is a lot nicer to keep things explicit or derive data with getters instead - like you did with `isLoading`.

```js
import { store } from 'react-easy-state'

const store1 = store({ value: 'x' })
const store2 = store({
  get value () { return store1.value }
})
```

Also in this particular case I don't see much value in storing the exact same information in two different places.

I hope this answered your question, I am not sure though. Let me know if I misunderstood you and feel free to show me your code if you would like some light review/tips later.

Thanks for the issue 🙂

**Comment by kiwi1342** [comment]
Thanks for your quick response. I was just experimenting with the library and I wanted to achieve exactly what you did in the first example but if I understood correctly I have to use the Observer Util right?

**Comment by solkimicreb** [comment]
> Using store2.value inside a view never gets the updated value

Are you sure about that? Here is [a minimal codesandbox demo](https://codesandbox.io/s/2pzm8042pj?module=%2Fsrc%2FApp.jsx) that does exactly that. It works for me and it should work, what version are you using?

Easy State **does not add new features to your state management / data handling** - like binding values together. It instead removes the restrictions - like the need for extra decorators or actions and reducers - that other libraries require.

Do not expect anything to happen that wouldn't happen in normal JavaScript. The only thing it does, is the automatic view update at the very end of your data manipulation. I could add data management enhancers - like data binding and automatic fetching - but from my experience they cause more trouble than good. (I did experiment with these for quite some time).

I hope this clarifies it a bit 🙂 Let me know if the getter example does not work for you. It is something that absolutely should work. It is plain JavaScript with the expectation of automatic view updates, exactly what Easy State is good at.

**Comment by kiwi1342** [comment]
You are right. I guess it was a codesandbox bug. I recreated the same example that wasn't working and it worked! I agree with you for avoiding extra decorators, in fact I think that mastering the getters is like using the `@computed` decorator in MobX (correct me if I'm wrong)

**Comment by solkimicreb** [comment]
Yep, it is exactly the same 🙂
