### ISSUE TITLE
Proxies polyfill

### ISSUE THREAD

**Issue by yamsellem** [solkimicreb/react-easy-state#34]
Hi,

As stated in the docs "`This library is based on non polyfillable ES6 Proxies. Because of this, it will never support IE`". Looking at something like [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill), proxies seems to already have some polyfill to handle IE9+ support.

Is there a reason why this polyfill would not work with react-easy-state? (_which part is non polyfillable, and is this for ever?_)

_ps. thanks for the great work: the simplicity of react-easy-state is a breeze!_

**Comment by solkimicreb** [comment]
Hi,

It does 'work' by replacing some errors with warnings in the polyfill, but it could never support `has` operations, `delete` operations and dynamic properties, which completely messes up arrays.

There is an enthusiastic guy who already replaced the errors and is working on adding a hacked array support in [this forked repo](https://github.com/lukeburns/proxy-polyfill). It should work with Easy State without any problems for this limited subset. You can try it out 🙂 

On the other hand, I wouldn't promote this as 'supporting' IE. This project will soon [evolve into a complete React 'framework'](https://github.com/solkimicreb/react-easy-state/issues/27), which relies pretty heavily in dynamic props. It could never support IE without some heavy restrictions.

**Comment by yamsellem** [comment]
Hi,

Thanks for your quick answer!

This [proxy polyfill fork](https://github.com/lukeburns/proxy-polyfill) seems pretty new, and I may be one of the first to try this out, so I think we may say it a experimental support for now on.

As I see, react easy state is a very thin layer on top of on `@nx-js/observer-util`.
I really like the idea of supporting observable through proxy, but I'm looking for a solution to support IE as well (_it is a matter of one year or two before IE could definitely be buried, but meanwhile, ~10% of our user are using IE11_).

May you recommend another 'more stable' approach to support IE?
As I see, it's a matter of making an object observable and calling `view.render` on every change.

I would really love to embrace this approach, instead of using `redux` or `mobx`, which IMO, are more complicated than the problem they're trying to solve.

Thanks a lot for your help.

**Comment by solkimicreb** [comment]
> As I see, it's a matter of making an object observable and calling view.render **on every change**.

This is the tricky part. There are no general change detection in JS apart from Proxies. I think your best bet is the Proxy polyfill or MobX while you have to support IE. Sorry about this, but there is really no way to hack around the limitations 🙁

**Comment by nuragic** [comment]
Hi! Perhaps you're already aware, but just in case: the author of MobX recently released a new state management lib that makes use of `Proxy` as well, and it has support for IE:   

https://github.com/mweststrate/immer

Dunno if it could be helpful in this case, but it ships with an ES5 compatible implementation to support those old environments. 🎩 👀 😄 

Cheers

**Comment by yamsellem** [comment]
@nuragic looking at [immer](https://github.com/mweststrate/immer) and [bey](https://github.com/jamiebuilds/bey) they seem to share react-easy-state's kiss philosophy which I love so much.

The IE compatibility seems crucial to me, for now (but in a couple of where, this restraint will be gone).

As you said, immer uses proxies too, so it can be a great source of inspiration to get a way for react-easy-state to work on the oldest (and ugliest) brother of all.

Seing more simple approches than the bloated redux to the store sharing question is clearly a relief.

**Comment by solkimicreb** [comment]
Sorry guys, I have to repeat the bad new 😄 Proxies are not polyfillable. Everything that works on ES5 and uses Proxies work with only a subset of what Proxies can do. Sadly easy-state requires more than these features and a polyfilled version would be pretty much useless.

**Comment by yamsellem** [comment]
@solkimicreb I remember now. It's all about support for `has` & `delete` operations and dynamic properties, which messes up arrays.

Maybe taking a look at how immer handles this can help. Because its doc stated that it handles arrays and don't rely on non polyfillable parts of proxies.

Sorry for looping around this matter once in a while, I would love to use react-easy-state, that's why ^_^

**Comment by Penspinner** [comment]
I'm looking through the [immer source code](https://github.com/mweststrate/immer/blob/master/src/immer.js#L67), and it looks like the es5.js file is used when Proxy is not defined. If you go into [es5.js](https://github.com/mweststrate/immer/blob/master/src/es5.js) and Ctrl/Cmd + F for 'delete', nothing shows up. Judging from that, the `delete` operator is not trapped when Proxy is not defined. Maybe es5 Immer is cloning the entire arg, if not, the majority of the the arg before passing it as draftState so that running a `delete` operator in draftState will not affect the original state?

The difference here is Immer will produce a new state based on whatever trappable mutations, but easy-state needs the ability to react to all traps on store mutations.

Please correct me if I'm wrong.

**Comment by solkimicreb** [comment]
Thanks for the explanation @Penspinner , it was on point. Closins this issues now, feel free to reopen it if needed.
