### ISSUE TITLE
Extending Store in Typescript

### ISSUE THREAD

**Issue by SukantGujar** [solkimicreb/react-easy-state#35]
Hi,

I am new to Typescript and this may be more appropriate question in a TS forum. However, while using `react-easy-state` in TS, I am not able to import its types, e.g. Store from the library. I need to extend my application's store, the use case is to define a common interface AppStore with well defined methods and properties. To achieve this, I am trying to extend the Store type and hence this issue.

Any suggestions? I thought the use case is simple enough to not warrant code, but would be glad to add some if needed.

Thanks!

**Comment by solkimicreb** [comment]
Hi,

Unfortunately I am a Typescript newbie 🙁 I will find out how to do this, it is something I should probably know too. Let me know if you find a solution in the meantime.

**Comment by SukantGujar** [comment]
One thing I have seen is that the types are exported along with the exported entities. E.g. the code for store can also export "Store" type.

An example:

```
  import * as React from 'react';

  export type Stop = () => void;

  export interface ITimerProps {
    interval: number;
    task: (stop: Stop) => void;
  }

  export class Timer extends React.Component<ITimerProps, object> {
    handle: number = 0;
    stop: Stop = () => {
      if (this.handle) {
        window.clearInterval(this.handle);
        this.handle = 0;
      }
    }
    invoke = () => {
      let {task} = this.props;
      task(this.stop);
    }
    componentDidMount() {
      let {interval} = this.props;
      this.handle = window.setInterval(this.invoke, interval);
    }
    componentWillUnmount() {
      this.stop();
    }
    render() {
      return (<div />);
    }
  }
```
This example exports `ITimerProps`, along with the component.

**Comment by SukantGujar** [comment]
So went through the code and noticed that the library is in pure JS. You do have types exported, but I am not sure how the Store type can be imported by my code 😃. If only a TS dev can pitch in here!

**Comment by solkimicreb** [comment]
Sure, you can post this anywhere! I didn't have time too look into this yet 🙁 but I did not forget it. The types are kept in a separate type definition file (defined by the `typings` field in package.json). I prefer to keep it in pure JS and add support for all type systems when needed (maybe someone will need flow support for example).

**Comment by SukantGujar** [comment]
So, I had to make these modifications to the type definitions file -
```
  declare module 'react-easy-state' {
    import { ComponentType } from 'react'

    type Store = object;

    // takes an object (optionally), wraps it in a transparent proxy and returns the proxy
    function store<Store>(obj?: Store): Store
    // takes class or function component and returns a class HOC
    function view<ComponentType>(comp: ComponentType): ComponentType
  }
```
As you would note, I had to explicitly declare a type for `Store`. This allows me to import `Store` from `react-easy-state` for extending my `AppStore` type. Other than that, I replaced `Comp` inline type with `ComponentType` imported from React, as that'd suffice here, unless the `view` adds some more over `ComponentType`.

If you are ok with these changes, I can submit a PR.

**Comment by solkimicreb** [comment]
Thanks for looking into this 🙂 I really appreciate it. Just a few questions:

- Why do you need the Store type when it is just a simple generic object?
- Do we still need `<Store>` and `<ComponentType>` in your solution?

I would gladly accept a PR btw.

**Comment by SukantGujar** [comment]
Currently Store is merely an alias of object. I thought of extending it to future proof my code, e.g. if the Store type is enhanced in some way. In TS/OOP it makes sense to extend from the same type as used in the consumed code.
If Store is frozen and will never be having any expected structure, then I can safely use object. In fact it would make sense to do away with it in the typings and simply use object, like ComponentType.

**Comment by solkimicreb** [comment]
That makes sense, but the store will never change the data that you passed to it. It will return the exact structure that you passed to it and this is something, that won't change.

The current type checks just ensure that everything is transparent (as it should be). It checks if `view` and `store` returns the exact structure that they received. It's not enough for them to be an object or a Component it has to be the same object and the same component, that they received as argument.

``js
 function store<Store extends object>(obj?: Store): Store
 function view<Comp extends ComponentType<any>>(comp: Comp): Comp
```

**Comment by SukantGujar** [comment]
> It's not enough for them to be an object or a Component it has to be the same object and the same component, that they received as argument.

Got that, thanks @solkimicreb. I will continue with using `object` to extend my AppStore for now. Closing this issue.
