### ISSUE TITLE
Store functions vs separate ones

### ISSUE THREAD

**Issue by vladshcherbin** [solkimicreb/react-easy-state#37]
Hey, @solkimicreb 

I've just discovered this library and decided to replace a few reducers and redux with it in my current project. Managed to do it with no difficulties and so far it works well. I've got a simple question, maybe opinionated:

```js
const notificationsStore = store({
  notifications: [],
  addNotification (message) {
    notificationsStore.notifications.push(message)
  }
})
```

vs

```js
const notificationsStore = store([])

function addNotification(message) {
  notificationsStore.push(message)
}
```

What do you think about this one, any pros/cons? What's your advice on this one?

**Comment by solkimicreb** [comment]
I just started to see people use the latter and I actually like it a lot. Edge case/feature wise it doesn't matter though. Theoretically the latter is faster, but it should be a super slight difference.

In my recent projects I tend to export the functions as named functions and export the store as the default export (or not export it at all, if I have a pure function interface).

Another pattern I started to use is hidden stores with a couple of functions and components for general global stuff (like loader below the app bar or notifications with snackbars).

```js
import React from 'react'
import { store, view } from 'react-easy-stack'
import { LinearProgress } from 'material-ui/Progress';

const loaderStore = store({
  isLoading: false
})

export function startLoading () {
  loaderStore.isLoading = true
}

export function stopLoading () {
  loaderStore.isLoading = false
}

export default view(() =>
  loaderStore.isLoading ? <LinearProgress color="secondary" /> : null
)
```

Then you can consume it by adding `<Loader />` components at places you want to (generally at one place) and you can call `startLoad()` and `stopLoad()` from anywhere to trigger the loaders (I trigger these functions in my API layer interceptor usually).

I hope to see some awesome patterns emerging in the future.

**Comment by vladshcherbin** [comment]
@solkimicreb very cool, thanks for your example.

I also used in my project the second variant with a separate store and exported named functions, really liked the simplicity and purity.

Maybe a small example can be added to the docs to show how simple it can be after messy redux reducers.

Thanks a lot for this library, feels like a breath of fresh air 🌱
