### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by FDiskas** [solkimicreb/react-easy-state#38]
would be cool to have typings for typescript
at least like so: 
```ts
declare module 'react-easy-state' {
  export function store(obj: any): any;

  export function view(Comp: any, ref: any): any;

  export namespace store {
    const prototype: {};
  }

  export namespace view {
    const prototype: {};
  }
}

```

**Comment by solkimicreb** [comment]
Hi!

The project already [has type definitions](https://github.com/solkimicreb/react-easy-state/tree/master/types) to work with stricter TS modes. Would you like to have these exported? Also see [this issue](https://github.com/solkimicreb/react-easy-state/issues/35) about the topic.

**Comment by FDiskas** [comment]
@solkimicreb sorry - everything is working correctly

**Comment by solkimicreb** [comment]
No worries 🙂
