### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by escobar5** [solkimicreb/react-easy-state#39]
How do you handle persistence of store objects? is there anything like redux persist? or do you have any suggestions about how to handle it?

**Comment by solkimicreb** [comment]
Hi!

Check out the `storage` object in [react-easy-params](https://github.com/solkimicreb/react-easy-params). It is a store which is auto synced with the localStorage. From the developer's viewpoint, it is a plain object that is persistent between sessions (it also triggers relevant renders on mutations, just like other stores). Persisted counter example:

```jsx
import React from 'react'
import { view } from 'react-easy-state'
import { storage } from 'react-easy-params'

storage.num = storage.num || 0
const increment = () => storage.num++

export default view(() => <p>The counter is at: {storage.num}</p>)
```

Easy Params will be a core part of the upcoming [react-easy-stack](https://github.com/solkimicreb/react-easy-state/issues/27).

**Comment by thebarty** [comment]
Hi guys,

I love the syntax and simplicity of the package, BUT I wish there was an EASY way to hook a global store up with localStorage. WITHOUT having to store it in the url via easy-params…

Something like https://www.npmjs.com/package/react-localstorage would be fine…

**Comment by solkimicreb** [comment]
Hi @escobar5 and @thebarty,

I am closing the issue. Feel free to reopen it, if I did not answer your questions.

**Comment by rytyr** [comment]
Hi @solkimicreb 
I really enjoy and recommend this package in our company, along with NextJS.

Does persistence option will be added in the future?
If no one working on this and persistence is deemed relevant/acceptable, I am planning to create a pull request for it. 

IMO, It will be great if we can do things such below:

```js
const options = {
   write: async (data)=>{ /** persist data (ex: localStorage.setItem or AsyncStorage.setItem  */ },
   clear: async ()=>{ /** clear persistence data (ex: localStorage.removeItem  or AsyncStorage. removeItem */ },
   load: async ()=>{ /** get persistence data (ex: localStorage.getItem  or AsyncStorage. getItem */ },
}

const localStore = store({ data: 'abcdefg' }, options)

// cleanup persisted value
localStore.__clear();
// reload from persistence layer
localStore.__load();

```
