### ISSUE TITLE
`view` cannot copy static defaultProps getter

### ISSUE THREAD

**Issue by Penspinner** [solkimicreb/react-easy-state#41]
```js
const defaultProps = { number: 0 };
let id = 0;

class SubComponent extends Component {
  static get defaultProps() {
    return { ...defaultProps, id: id++ };
  }

  // Other methods
}

export default view(SubComponent);
```

This throws an error for me: `Uncaught TypeError: Cannot set property defaultProps of ...`
It looks like `view(BaseComponent)` can't copy a static getter property.
Here is a Codesandbox link to an example of the error: https://codesandbox.io/s/x209v97ypq

[MDN error link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only).

Is there a way to solve this?

---
**Edit 1**

Was just looking at view.js again. Could `ReactiveHOC` extend the passed in argument `Comp` instead of `BaseComp`? If so, would it still be necessary to copy the static properties to `ReactiveHOC` if it extended the `Comp` argument? 

```js
return class ReactiveHOC extends BaseComp {
    static displayName = Comp.displayName || Comp.name;
    static contextTypes = Comp.contextTypes;
    static childContextTypes = Comp.childContextTypes;
    static propTypes = Comp.propTypes;
    static defaultProps = Comp.defaultProps;
    ...
}
```

Could that just be
```js
return class ReactiveHOC extends Comp {
    ...
}
```
?

---
**Edit 2**

Nvm my question in Edit 1. I realized that making a HOC extending a functional component does not necessarily make it extend React.Component.

Would it be possible to check the value `isStatelessComponent` before copying the static properties?
So if `isStatelessComponent` is `true`, copy the static properties, otherwise make `ReactiveHOC` extend from `Comp` without copying static properties..?

**Comment by solkimicreb** [comment]
Hi!

Thanks for the issue and the solution 🙂[v5.0.1](https://github.com/solkimicreb/react-easy-state/releases/tag/v5.0.1) is out with the fix, I did exactly what you suggested in Edit 2.

I am closing this, feel free to reopen if the new behavior still has issues.
