### ISSUE TITLE
TypeScript class support

### ISSUE THREAD

**Issue by josh-endries** [solkimicreb/react-easy-state#42]
Is there a way to get this to work with TS classes? It works if you use it as a function:

    const View1 = ez.view(() => <div>{appState.count}</div>);

However I haven't been able to get it to work with `class`, e.g.:

	class View2 extends React.Component<{count:number}, {}>{
		public render() {
			return <div>Hello from View2 {this.props.count}</div>;
		}
	}

	const View3 = ez.view(View2);

That gives me:

    Uncaught TypeError: Class constructor View2 cannot be invoked without 'new'
        at new ReactiveHOC (es.es5.js:27)
        at constructClassInstance (react-dom.development.js:6801)
        at updateClassComponent (react-dom.development.js:8336)
        at beginWork (react-dom.development.js:8982)
        at performUnitOfWork (react-dom.development.js:11814)
        at workLoop (react-dom.development.js:11843)
        at HTMLUnknownElement.callCallback (react-dom.development.js:100)
        at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
        at invokeGuardedCallback (react-dom.development.js:187)
        at replayUnitOfWork (react-dom.development.js:11318)

I tried making a decorator but haven't figured that out yet unfortunately, all sorts of typing problems (I haven't done anything with decorators yet), but that seems like the ideal way to use it... In case it helps, my `tsconfig.json` is:

	{
		"compilerOptions": {
			"experimentalDecorators": true,
			"jsx": "react",
			"moduleResolution": "node",
			"target": "es6"
		},
		"include": [
			"src/app/ts/*.ts",
			"src/app/tsx/*.tsx"
		]
	}

**Comment by josh-endries** [comment]
Thanks for the response. I'm not 100% sure how, but the error went away and I can't make it come back...however my wrapped view isn't incrementing like the function one is. Maybe my script is being set up in the wrong order? This is the full script:

	import * as React from 'react';
	import * as ReactDOM from 'react-dom';
	import * as ez from 'react-easy-state';

	const appState = ez.store({ count: 0 });

	class View extends React.Component<{count:number}, {}>{
		public render() { return <div>Hello {this.props.count}</div>; }
	}
	const SimpleView = ez.view(() => <div>Hello {appState.count}</div>);
	const EasyView = ez.view(View);
	const rootNode = document.body.appendChild(document.createElement('div'));
	ReactDOM.render(<div><SimpleView/><EasyView count={appState.count}/></div>, rootNode);
	setInterval(() => { appState.count += 1; }, 3000);

The SimpleView increments, but EasyView sits at 0.

**Comment by josh-endries** [comment]
Hmm the stopwatch sample works so it must be something with my organization.

**Comment by solkimicreb** [comment]
Change it to:

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as ez from 'react-easy-state';

const appState = ez.store({ count: 0 });

class View extends React.Component<{}, {}>{
	public render() { return <div>Hello {appState.count}</div>; }
}
const SimpleView = ez.view(() => <div>Hello {appState.count}</div>);
const EasyView = ez.view(View);
const rootNode = document.body.appendChild(document.createElement('div'));
ReactDOM.render(<div><SimpleView/><EasyView/></div>, rootNode);
setInterval(() => { appState.count += 1; }, 3000);
```

Your function component used `appState` directly, while your class component only used a dereferenced primitive from it (`count`) as a prop. 

Alternatively, you can do:

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as ez from 'react-easy-state';

const appState = ez.store({ count: 0 });

class View extends React.Component<{count:number}, {}>{
	public render() { return <div>Hello {this.props.count}</div>; }
}
const SimpleView = ez.view(() => <div>Hello {appState.count}</div>);
const EasyView = ez.view(View);
const App = ez.view(() => <div><SimpleView/><EasyView count={appState.count}/></div>);
const rootNode = document.body.appendChild(document.createElement('div'));
ReactDOM.render(<App />, rootNode);
setInterval(() => { appState.count += 1; }, 3000);
```

Just make sure to wrap the view with `view` if it uses the store directly. In your case there was an appState usage in `ReactDOM.render`, which was not observed by `view`.

**Comment by josh-endries** [comment]
Hmmm when I do this it doesn't increment:

    const EasyApp = ez.view(() => <div><App state={appState} /></div>);
    ReactDOM.render(<EasyApp/>, rootNode);

However this works:

    const EasyApp = ez.view(() => <div><App state={appState} />{appState.count}</div>);
    ReactDOM.render(<EasyApp/>, rootNode);

With the reference to `.count` in the second usage of EasyApp, *both* counters incremented. Wrapping it in another level (`store = { state: { count: 0 } }` and passing around `state`) doesn't work either.

Does it only track direct usages of state properties and not the state object itself and/or references to its children? In other words, only properties on the state object that are directly used get tracked?

**Comment by solkimicreb** [comment]
What is your whole code for the first (none working) example? Did you also wrap the `App` component - which uses `appState.count` - with `view`? If not, it won't update. In your second case it updated, because its parent updated and React re-rendered its whole subtree. You should wrap every component - which uses props from the state - with `view`.

Easy State tracks property usage on the state object (or it's children). I don't really see what else it could track. What would be your expected behavior in this case: `<App state={appState} />`, should it re-render when the `appState` is mutated in any way?

Views are re-rendered when a state property - used by them - changes value. This means it tracks with a maximal precision. It only re-renders if the view would yield a different result, because a **relevant part** of the state changed. If you wrap all of your components with `view` you should not have to think about this though.

The reactivity might not be trivial at the start, but you can quickly get the hang of it. I will try to update the docs to make it more obvious at start. Can you explain what do you find confusing or what works against your expectations and what behavior would you naturally expect in those cases?

Thanks 🙂

**Comment by josh-endries** [comment]
Sorry for the delay, most of my free time is on the weekends.

I meant it could potentially track properties of the state object but not the object itself, i.e. iterate over the properties and proxy those, but not the object that gets passed in. That seems a weird way to do it, though, so I was guessing it doesn't do that, and it sounds like it doesn't.

For `<App state={appState}/>` I would think one of two things depending on how it works:

1. In the simple case, any time `appState` itself changes (e.g. new properties), or child properties on it change, `App` re-renders and React handles rendering children. Basically in this case it's just normal React usage with a smart component.
2. In the complex case, if `appState` itself changes, `App` is re-rendered, however if properties *on* `appState` change (and `App` doesn't reference those properties directly), then `App` doesn't re-render. Instead, it automatically tracks which children *do* use properties on `appState` and those get re-rendered if their used properties change.

In both cases I would expect to only wrap the `App` component. It sounds like this might be true for case 1 but not case 2. Basically, I want to wrap smart components only and have children either update via React's normal processes or have it automatically figure out which children to re-render based on their state usage. It sounds like case 1 is how it works, which should be fine, I'm just looking for smart components really. I don't want to have to wrap all children of the smart component, though, and it sounds like I shouldn't need to (React just handles it from the smart component re-render).

This is the code that doesn't increment (it just displays zero):

	import * as React from 'react';
	import * as ReactDOM from 'react-dom';
	import * as ez from 'react-easy-state';

	interface AppState { count: number; }

	class View extends React.Component<{ count: number }, {}> {
		public render() {
			return <div>{this.props.count}</div>;
		}
	}

	class App extends React.Component<{ state: AppState }, {}> {
		public render() {
			return <View count={this.props.state.count} />;
		}
	}

	const state = ez.store({ count: 0 }) as AppState;
	const EasyApp = ez.view(() => <div><App state={state} /></div>);

	ReactDOM.render(<EasyApp />, document.body.appendChild(document.createElement('div')));

	setInterval(() => { state.count += 1; }, 3000);

I also tried `ez.view(() => <App state={state} />)` thinking that the wrapping `div` was a problem, but that had no change. I also tried this (without the arrow function):

	const EasyApp = ez.view(<App state={state} />);

	ReactDOM.render(<EasyApp />, document.body.appendChild(document.createElement('div')));

But that gives me an error in `ReactDOM.render` saying "JSX element type 'EasyApp' does not have any construct or call signatures", I guess because the `view` function is taking in/returning an instance rather than the "class"/constructor, though I wasn't able to mess with the typing in a way to make it work. If I just jam `any` all over the place to make it compile as if it were a constructor, I get this at runtime:

	Uncaught TypeError: Comp is not a function
		at ReactiveHOC.render (es.es6.js:34)
		at runAsReaction (es.es5.js:93)
		at ReactiveHOC.reaction [as render] (es.es5.js:147)
		at finishClassComponent (react-dom.development.js:8389)
		at updateClassComponent (react-dom.development.js:8357)
		at beginWork (react-dom.development.js:8982)
		at performUnitOfWork (react-dom.development.js:11814)
		at workLoop (react-dom.development.js:11843)
		at HTMLUnknownElement.callCallback (react-dom.development.js:100)
		at Object.invokeGuardedCallbackDev (react-dom.development.js:138)

That seems like logical syntax to me but I'm not really sure if it's supposed to work or not, TS's distinction of instance and constructor get in the way. The most natural usage would be a class decorator, or possibly a base class, in my opinion.

**Comment by Penspinner** [comment]
I've had a similar concern as josh-endries'. I wanted to wrap smart components/containers in `view`, but not presentational components. But if I pass an object from a container to a component as a prop, mutating that passed in object will not cause the component to re-render. Here is an example: https://codesandbox.io/s/x209v97ypq

However, in my actual projects, I just wrap my presentational components with `view` if it doesn't re-render.

**Comment by josh-endries** [comment]
Yeah, my original thought was the same I think--that mutating the child object would bubble up the mutation event to the parent state object, which is passed into the container component, and triggers a re-render of the container component, which trickles down via React to the presentation components.

Unfortunately it looks like Proxies don't automatically watch children and bubble up changes to parents, so you would need to proxy all initial objects separately and proxy any added objects automatically. I've done this before, it can be a pain, but it's not the default behavior. I'm not sure if `observable` handles this or not. Or I could just be plain wrong. If you have a flat state object it might work.

**Comment by solkimicreb** [comment]
I see the issue now and I think it can be considered a bug and it can be fixed. I will tweak the behavior to re-render the container on your use cases and give you some more context about the root of the issue, but I won't have time to do it for a bit more than a week (I'm on vacation with limited internet access and time).

Thanks for clearing this up 🙂

**Comment by solkimicreb** [comment]
Hi!

Sorry for the long silence (I was on vacation). The issue here is my false impression of React's scheduling. See the below code for some explanation.

```js
import React from 'react';
import ReactDOM from 'react-dom';

const Child = () => {
  console.log('render child start');
  const result = <div>Child</div>;
  console.log('render child end');
  return result;
};

const Parent = () => {
  console.log('render parent start');
  const result = <Child />;
  console.log('render parent end');
  return result;
};

ReactDOM.render(<Parent />, container)
```

I thought this would log:

- render parent start
- render child start
- render child end
- render parent end

Instead it logs:

- render parent start
- render parent end
- render child start
- render child end

Which means that the parent render does not call the child render directly, instead there is a common function - further up the stack - which calls both of them one after another.

The underlying observer library observers the whole sync stack below the observed function (which is a `view` wrapped component render in our case). If the render would call child renders directly this issue would not exist. Easy State would observe the parent render and all child renders below them and re-run the parent render when any store property - used inside any of the renders below the parent - is changed.

To fix it I would have to lift the observed function up to the function that calls the parent and child renders. Explained in code:

```js
// I observe this function currently when you wrap it with `view`, but it never calls Child directly
function Parent () {
  return <Child />
}

function Child () {
  return <span>Child</span>
}

// I should observe this function instead
function internalReactRenderer () {
  renderParent()
  renderChild()
}
```

I hope this makes sense. I am looking for the proper React hook to observe instead of the render (and I hope it exists 😄).

Ultimately I will get back to my own framework, when I am satisfied with react-easy-state and the upcoming react-easy-stack. Working around existing frameworks is pretty painful.

**Comment by atrauzzi** [comment]
Obviously it depends on using webpack, and maybe other module loaders support aliasing, but I've just done this and it works:

```
        alias: {
            "react-easy-state": `${__dirname}/node_modules/react-easy-state/dist/es.es6.js`,
        }
```

**Comment by solkimicreb** [comment]
I did some research and thinking. This behavior won't be tweaked, you should wrap ALL components in `view` to make 100% sure that easy-state will work well.
