### ISSUE TITLE
Batch store updates

### ISSUE THREAD

**Issue by lostpebble** [solkimicreb/react-easy-state#43]
Hi there,

Thanks so much for this awesome library, loving the drop and go nature of it.

One issue I am facing at the moment is that of making store updates and those updates are triggering a render on each and every property I update. I would like to be able to batch an update to the store, i.e. edit multiple individual properties before it triggers its re-render of the view.

I'm currently using it like this:

```
export const UserStateStore = store<IUserStateStore>({
  initialUserCheckRan: false,
  isLoggedIn: false,
  user: {
    authLevels: [EAuthLevel.ANONYMOUS],
    photoUrl: null,
    username: "",
    email: "",
    uid: "",
    authNodeIds: [],
  },
  loginUser(user) {
    UserStateStore.user = user;
    UserStateStore.isLoggedIn = true;
    UserStateStore.initialUserCheckRan = true;
  }
});
```

As you can see I have that `loginUser()` function there. When that is called I'd like to update the user object, and the logged in state and set that our initial check for a currently logged in user has been run.

But each of those three changes are triggering a re-render in my view which is set to listen for those properties.

Is there anything in `react-easy-state` which works similar to `mobx` actions? I recall the actions in MobX waiting until the action function has finished before updating views.

**Comment by solkimicreb** [comment]
Hi!

Where do you call the `loginUser` function from?

Easy State has 'automatic batching', normally you should not have to worry about batching yourself. It uses `setState` behind the scenes, while MobX uses `forceUpdate`. `forceUpdate` always triggers an immediate synchronous render, while `setState` may batch renders.

Currently React is batching `setState` calls in event handlers (or functions called synchronously from event handlers) and triggers synchronous renders otherwise. This is why I asked where do you call your `loginUser` function from. If you call it from an event handler - like as a result of a button click - it should trigger a single render only.

In the beginning I used a custom scheduler instead of delegating to React with `setState`, but I decided to remove it since it resulted in inferior performance on benchmarks and React's own scheduler is going to get a lot more batching pretty soon (async mode and Fiber).

Thanks for the issue, I can help a bit more after you answer my opening question 🙂

**Comment by lostpebble** [comment]
Ah right, well I'm using it pretty much exactly like this (I'm calling `loginUser()` from outside my component in a callback function that responds to user login state):

```
export const UserStateStore = store({
  initialUserCheckRan: false,
  isLoggedIn: false,
  user: {
    authLevels: [EAuthLevel.ANONYMOUS],
    photoUrl: null,
    username: "",
    email: "unset",
    uid: "",
    authNodeIds: [],
  },
  loginUser(user) {
    UserStateStore.user = user;
    UserStateStore.isLoggedIn = true;
    UserStateStore.initialUserCheckRan = true;
  }
});

Firebase.auth.onAuthStateChanged((user) => {
  console.log(`Auth state changed`);

  if (user != null) {
    UserStateStore.loginUser({
      email: user.email || "unset",
      authLevels: [EAuthLevel.ADMIN, EAuthLevel.ARCHITECT],
      authNodeIds: [],
      photoUrl: user.photoURL,
      uid: user.uid,
      username: user.displayName || "user",
    });
  } else {
    UserStateStore.isLoggedIn = false;
    UserStateStore.initialUserCheckRan = true;
  }
});

export class StoreComponent extends React.Component {
  render() {
    console.log(`Rendering this component with user email set: `, UserStateStore.user.email);
    return this.props.children(UserStateStore);
  }
}

export default view(StoreComponent);
```

After making use of the wrapped component somewhere in my app, my console looks like this:

```
Rendering this component with user email set:  unset
Auth state changed
Rendering this component with user email set:  paulmyburgh88@gmail.com
Rendering this component with user email set:  paulmyburgh88@gmail.com
Rendering this component with user email set:  paulmyburgh88@gmail.com
```

So it seems like its outside the context of the kind of event handlers you refer to?

**Comment by solkimicreb** [comment]
> So it seems like its outside the context of the kind of event handlers you refer to?

Yes, it is.

I may add back the custom scheduler to the library, which batches `setState` calls the happen maximum once per synchronous call stacks. You wouldn't have to change anything in your current or future code and the above issue would never happen again.

The code is already done, you can find it [here](https://github.com/solkimicreb/react-easy-state/blob/feat/scheduler/src/view.js). It is a small change without issues or breaking tests, but it does cause some subtle changes (with testing and SSR) which need a bit more consideration. I am also doing a performance profiling round before making the decision, but a quick run suggested that it has a slightly improved performance even for cases where `setState` is batched by React anyways.

I can hopefully merge this in tomorrow 🙂 (After that I will be less responsive for 2 weeks)

**Comment by lostpebble** [comment]
Okay, great! Thanks @solkimicreb 🙂

And nice to hear it might even add some performance.

I will be making use of SSR as well for my project in the future, so quite curious as to what those subtle changes are you refer to as well.

**Comment by solkimicreb** [comment]
Hi!

Just to give some updates on this: it works nicely and batches correctly, but there is a very specific edge case that React does not like.

React batches updates in event handlers by default. If you have an event handler where you call `setState` just once for a lot of DIFFERENT components, it is still batched into a single update in React. Doing this outside of event handlers requires me to wrap the batched `setState` calls in `unstable_batchedUpdates` or `flushSync`, which are unfortunately both `react-dom` specific functions. There are alternatives in react native too, but going down this way would mean I have to split the library into separate DOM and native builds.

I try to avoid that, but I agree that improving the batching is important.

**Comment by solkimicreb** [comment]
Hi @lostpebble!

In the end I decided to do not add default custom batching and wait for the React guys until they finish their own batcher (hopefully React 17). You can find out more and learn how to batch manually (like MobX actions) in [this new docs section](https://github.com/solkimicreb/react-easy-state#my-component-renders-multiple-times-unnecessarily).

I am closing the issue, feel free to reopen it.
