### ISSUE TITLE
fuzzy search with fuse.js not updating in view

### ISSUE THREAD

**Issue by surfjedi** [solkimicreb/react-easy-state#51]
Has any one used react-easy-state with fuse.js for a fuzzy search?

http://fusejs.io/

1. I assign a store to do a cities fuzzy search 
`const localStore = store({ cities: [], displayedCities:[], name:'thing'});`
2. have a fuzzy filter on keydown in the input.  Logging the localStore shows the expected out put, by UI won't show changes in the array. Athough will update localStore.name..
`
  fuzzyFilter(event){
      let value = event.target.value;
      var options = {
        keys: ['name']
      }
      var fuse = new Fuse(localStore.displayedCities , options)

      let result = fuse.search(value)
      console.log(result);
      localStore.displayedCities = result;

      localStore.name = value;
      console.log(localStore);

    }

`

any ideas?

**Comment by solkimicreb** [comment]
Hi! Using the lib for fuzzy search should not make any difference.

`var fuse = new Fuse(localStore.displayedCities , options)` Shouldn't this be `var fuse = new Fuse(localStore.cities , options)`? I don't think this is the issue though.

Could you also copy your view (Component) here?

**Comment by kempjeng** [comment]
I have an issue that may be somewhat related an potentially the cause of this issue.

I have a SPA that uses react-router.  If I wrap a component in a view, it will cease to trigger updates to the sub components.  That is:

`export default Layout`
will trigger updates

`export default view(Layout)`
will not trigger updates.

I've also been able to produce the same issue with other high order components (HOC).  I have a wrapper/decorator called `withResponsiveMode` that will inject the page size.  If I write:

`view(withResponsiveMode(LoginPage))` it will fail to render updates from the store.

however:

`withResponsiveMode(view(LoginPage))` will render updates.

**Comment by solkimicreb** [comment]
Let me know if withRouter from your linked comment helps here. If not, I will look into it.

**Comment by solkimicreb** [comment]
I am closing it, since the issue was inactive for a long time. Feel free to reopen if you have any related questions.
