### ISSUE TITLE
Best practices for third party / external components

### ISSUE THREAD

**Issue by naturalethic** [solkimicreb/react-easy-state#53]
Is there a current best practice for wrapping third party component libraries in `view` so that they will react to changes in state properties?

**Comment by solkimicreb** [comment]
Sorry for the super late response.

I think I see your issue, but an example would be really helpful. External libraries are usually written in a way that they update when you change their props. They rarely expect to be updated based on deep prop mutation.

In case they somehow depend on these cases, a dirty workaround would be to 'use' the passed down piece of state in your parent component too, to make it re-render itself and the 3rd party child on mutations. Like this:

```jsx
import { ThirdParty } from 'third-party'

const MyComp = view(() => {
  // imitate using user.name here, if you would like ThirdParty to re-render on name changes
  const dummy = appStore.user.name
  return <ThirdParty user={appStore.user} />
})
```

Another possibly more elegant way would be to create shallow clones, which basically converts easy-state's mutation based change detection to React's reference based detection.

```jsx
import { ThirdParty } from 'third-party'

const MyComp = view(() => {
  // this uses every property of the user while cloning it, so it re-renders both components on user mutations
  const user = Object.assign({}, appStore.user)
  return <ThirdParty user={appStore.user} />
})
```

**Comment by naturalethic** [comment]
Do you absolutely need cookies?  Or could use use session/local storage?  If so you could try https://github.com/solkimicreb/react-easy-params instead, which complements this package.

Otherwise, you can try just double wrapping like this:

`withCookies(view(comp))`

**Comment by solkimicreb** [comment]
Hi! Sorry for the long silence, I was on holiday.

What kind of error do you get when you double wrap? Did you try double wrapping with "both order"? It is strange that it is not working with double wrapping.

**Comment by vineeth-cnbr** [comment]
It's alright!

`withCookies(view(App))` worked. It was showing errors before. But i may have been mistaken. 

`view(withCookies(App))`  didn't work. It showed an error saying 

> Comp is not defined

Thanks Guys! @solkimicreb @naturalethic

**Comment by solkimicreb** [comment]
This question has a new [dedicated docs section](https://github.com/solkimicreb/react-easy-state#usage-with-third-party-components) now. I am closing this issue, feel free to reopen if you have more related questions.
