### ISSUE TITLE
Sharing. Auto-add getX and setX, private properties, bind this and more.

### ISSUE THREAD

**Issue by lishine** [solkimicreb/react-easy-state#56]
Hi people!

Sharing new code that I wrote and just started to use.
Interesting to hear your opinion.

```
import { store as reStore } from 'react-easy-state'

export function store(init, actions) {
	let Private = reStore(init)
	let Public = {}

	Object.entries(init).forEach(([property, initValue]) => {
		const setProperty = `set${_.upperFirst(property)}`
		if (!actions.hasOwnProperty(setProperty)) {
			const ss = function(s) {
				Private[property] = s
			}
			Private[setProperty] = Public[setProperty] = ss.bind(Private)
		}

		const getProperty = `get${_.upperFirst(property)}`
		if (!actions.hasOwnProperty(getProperty)) {
			const gg = function() {
				return Private[property]
			}
			Private[getProperty] = Public[getProperty] = gg.bind(Private)
		}
	})

	Object.entries(actions).forEach(([actionName, actionValue]) => {
		Private[actionName] = Public[actionName] = actionValue.bind(Private)
	})
	return Public
}
```

Use it like this:
```
export const Store = store(
	{
		property1: '',
		property2: '',
	},
	{
		getProperty2() {
			const ret = this.property2
			// do something
			return ret
		},
		setProperty2(s) {
			const newValue = s
			// do something
			this.property2 = s 
		}
	}
)

```

The public view of the store:
```
{
	getProperty1() {
		return this.property2
	},
	setProperty1(s) {
		this.property2 = s 
	},
	getProperty2() {
		const ret = this.property2
		// do something
		return ret
	},
	setProperty2(s) {
		const newValue = s
		// do something
		this.property2 = s 
	}
}

```
- So, getX and setX auto-added if they are not provided.
- The publicly accessible store can't access the properties directly.
- But the methods can access them with this.
- Limitation: No arrow functions. 
- More possibilities: auto add init/reset function, non-observable properties
- *** Actually, I will probably cancel the privatization. I did it in order to enforce setting with setX only. But I want to access the property by store.property. But I then I have to auto-add getter, getter have to be with the same name, and that is the problem. So I cancel the privatization.  
- *** Maybe adding setX is also stupid, just do store.x = ...

**Comment by ivan-kleshnin** [comment]
Why not just write those internal lines on the client side? Such methods add nothing except extra bundle bytes IMO.
