### ISSUE TITLE
Explain why everything must be wrapped

### ISSUE THREAD

**Issue by SwiftOne** [solkimicreb/react-easy-state#6]
Multiple places in the documentation you say something like "Make sure to wrap all of your components with easyComp - including stateful and stateless ones - before you export them."

Why?  If I have a stateless component with no added methods (say, a simple function-based component) am I _required_ to wrap it, or is it just suggested?

**Comment by solkimicreb** [comment]
Thanks for the issue!

I can't give a deep explanation there - as it would lead too much into the internals - but I will expand that section a bit more tomorrow.

Basically the wrappers instrument the hidden reactivity. If you do not wrap a component, you risk having it not properly render on store mutations. If you are a confident user, you can decide when it is really needed, but it is much simpler and safer to wrap all comps before the export. This is also the way MobX does it.

**Comment by SwiftOne** [comment]
That's a perfectly complete explanation - I was just looking to know if it was (1) truly required, and (2) if it is required, what would the symptom be if/when I forgot (so I would know to check for that).

Thanks for the quick response!

**Comment by solkimicreb** [comment]
I added a very short explanation. I think I will refactor the docs (maybe even outsource it an external page) with time based on feedback.

I am closing the issue now. Feel free to reopen it, if you think it should be a bit more verbose.

Thx for the issue again (:
