### ISSUE TITLE
Programmatic integration?

### ISSUE THREAD

**Issue by matthew-dean** [solkimicreb/react-easy-state#61]
The documentation notes that re-render will happen automatically as a result of certain values changing. Is there a way to programmatically subscribe to those store updates (by key) to trigger events other than render?

**Comment by solkimicreb** [comment]
There is a way. Easy State is a thin wrapper over a more generic library - called [observer-util](https://github.com/nx-js/observer-util).

You can make custom reactions for store changes with the `observe` function.

```js
import { store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const person = store({ name: 'Bob' })

// this logs person.name whenever it changes
observe(() => console.log(person.name))
```

Does this answer your question?

**Comment by matthew-dean** [comment]
Yeah that helps! Thanks!
