### ISSUE TITLE
Memoized Getters

### ISSUE THREAD

**Issue by mattmccray** [solkimicreb/react-easy-state#62]
I understand that you think MobX's memoized `@computed` getters are an "anti-pattern."( I don't think I agree... I could be convinced of such, but I'd need a good supporting argument.)

Regardless, there *are* times when the derived state needs to be computed and cached (to prevent expensive and unnecessary processing)... While straw-man examples are generally odious, let's go with this anyway:

```js
const searchStore = store({
    results: [],
    filter: '',
    get filteredResults() {
        if(searchStore.filter == '')
            return searchStore.results
        else
            return searchStore.results.filter(applyFilter(searchStore.filter))
    },
    get count() {
        return searchStore.filteredResults.length
    }
})
```

In this example, let's say you display `searchStore.count` in multiple  `view` components.

What is the best way to prevent the repeated calculating of  `searchStore.filteredResults` in a non-obnoxious way? ;-)

## Observer Approach?

```js
// An observer?
const searchStore2 = store({
    results: [],
    filter: '',
    filteredResults: [],
    get count() {
        return searchStore.filteredResults.length
    }
})

// I think `observe` is from '@nx-js/observer-util', but 
// perhaps exposing this from 'react-easy-state' would be useful?
observe(() => {
    const { filter, results } = searchStore2
    searchStore2.filteredResults = (filter != '')
      ? results.filter(applyFilter(filter))
      : results
})
```

This feels ugly, but I think it should work...

Any ideas for a better/cleaner solution?

**Comment by solkimicreb** [comment]
> I understand that you think MobX's memoized @computed getters are an "anti-pattern."( I don't think I agree... I could be convinced of such, but I'd need a good supporting argument.)

I think memoizing **every getter** is an anti-pattern. Memoization has its place (computationally intensive frequently invoked functions). This and the fact that there are tons of excellent memoization libraries led me to this decision. I think you should just use one of the popular memoization libs when you need it. A quick googling led me to these: [a fast one](https://github.com/leobalter/fast-memoize), [one with a nice decorator API](https://github.com/leobalter/fast-memoize).

About the observer approach:

> This feels ugly, but I think it should work...

Yep, it is ugly and you should not do this 😄. Having a chain of automatic reaction will blow your system up and make super hard to reason about data flow. You should never update data automatically based on other data - but derive it in (potentially memoized) getters instead. Reactions are designed to execute side effects on data changes (like rendering). These side effects are usually the last step of the data flow and they do not serve as a data source for other places.

**Comment by solkimicreb** [comment]
Yep, easy state does not break memoization. You should try to use your chosen lib with it.

The idea is to have no other built in feature than transparent reactivity but do not impose any restriction either. Easy state should work together with other js libs without hacking them.

**Comment by solkimicreb** [comment]
Is it working as expected for you?

**Comment by solkimicreb** [comment]
I am closing this, feel free to reopen if your issue was not solved.
