### ISSUE TITLE
Do recursive elements not re-render?

### ISSUE THREAD

**Issue by Dairnon** [solkimicreb/react-easy-state#63]
I've wrote a recursive react system that uses a react node that filters through a list of items from a store, and filters out a list based on type (folder, item) and path (used to tell how to nest itself for the hierarchy)

I wrapped my recursive node in a view, and then tried setting it to read its own property from within the store using a passed down node prop ID but it doesn't seem to wanna read any changes...

The recursive node element produces more versions of itself (based on filtering), and passes down ID's based on what it filters to each new node.
Each node then uses that ID to read from the store (this was my second approuch... vs just passing down each new nodes store data as a prop... i realized that doing it that way would probably prevent re-rendering (which it did)) However I wasn't expecting the ID look up of the original store to do the same as well.

Is easy-state render not capable of having nested recursive nodes read from id'd objects and or arrays of objects for its own changes?

The start of the recursion works fine (the first level where I first create the recursive nodes in the parent)
but every level down doesn't update.

BTW I love your library.. its made things much easier compared to that of mobx... I'm just having some troubles getting recursive elements to re-render. 

I'm hoping you can help me find a solution for this problem. :)

**Comment by solkimicreb** [comment]
Recursive elements do work but they are a bit ugly. You have to make sure to use the Reactive (`view` wrapped) element inside the element itself recursively.

```
const ReactiveRecursive = view(Recursive)

function Recursive () {
  // make sure you don't use raw <Recursive /> here
  return <ReactiveRecursive />
}

export default ReactiveRecursive
```

**Comment by Dairnon** [comment]
Thank you so much, that solved my issue! I appreciate the fast response!
