### ISSUE TITLE
Comparing previous state value and finding out which state changed

### ISSUE THREAD

**Issue by AntonioRedondo** [solkimicreb/react-easy-state#64]
Hi Miklos,

Kudos to your library. Really impressive. It's surprising how easily it handles state management in React.

I however came across with an issue that it may be a blocker for some React projects: you cannot compare the previous value of a state with its new one. This is necessary in order to know which state changed.

My use case is actually quite simple and common: I am waiting for a state to change (a string for example). When this state changes I'll fire an async function that will fetch data and when it resolves it will update the state. The problem is that I don't know which state changed, so if I'm listening to more than one state in a component, requests will be fired even when the string I am interested in didn't change as changing one single state will fire component life-cycle methods.

```javascript
import myStore from "./myStore"

class MyComponent extends React.Component {
    componentDidUpdate() {
        // How can I do something like this with react-easy-state?
        if (myStore.state1 !== myStore.prev.state1) this.fetchDataAndUpdateState2() 
    }

    render() {
        // How do I know if it's state1 or state2 the state changed?
        return <div>{myStore.state1} {myStore.state2}</div>
    }
}
```

**Memoization** can be a solution. **Local state** is another. But I don't find these solutions optimal. Sometimes you just need to know which state was the one changed.

This issue was already briefly discussed on https://medium.com/@ocorsomauro/what-about-component-lifecycle-methods-8e19ad61d816 but with no solution in the end.

Any insight on this?

**Comment by solkimicreb** [comment]
Hi!

You can set up automatic detailed reactions to fire network request on specific changes with the underlying observer-util library. This is basically the same idea without polluting the view with state and network logic. I will send an example when I get to my computer.

I wouldn't do this though. I know that what you described is a common pattern (it is even mentioned in the react docs), but I think automatically fetching data on data changes leads to magical data propagation chains. Reactions are meant to be at the very end of this chain to keep the flow reasonable. I would simply call the api endpoint together with the related state change instead of setting up some filtered reaction.

I might miss something important though. Can you provide the exact use case you ran into?

Thanks!

**Comment by AntonioRedondo** [comment]
There is no specific piece of code. At my company we're discussing which is the state management library we're gonna choose for a new React project. `react-ease-state` is leading the race as we want to avoid using Redux giving how verbose and complicated is for simple uses cases in both development and testing.

I think I get your idea now. You're right, the view should and can be independent from data handling. So your suggestion is the view should update its own state, let's say `searchString`, and then, another piece of code tasked with data retrieving should listen to changes to this `searchString` state and update a `results` state, state that will be shown on the view but ultimately it won't be this view who will decide to execute some action. Am I right?

Still, I am looking forward to the solution of this use case with the `observer-util` library.

**Comment by solkimicreb** [comment]
> I think I get your idea now. You're right, the view should and can be independent from data handling. So your suggestion is the view should update its own state, let's say searchString, and then, another piece of code tasked with data retrieving should listen to changes to this searchString state and update a results state, state that will be shown on the view but ultimately it won't be this view who will decide to execute some action. Am I right?

Yes. You can create custom reactions with the [observer-util](https://github.com/nx-js/observer-util) lib.

```jsx
import React from 'react'
import { view, store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const appStore = store({
  searchString: '',
  data: []
})

function fetchData () {
  fetch(`myPage.com?search=${appStore.searchString}`)
    .then(res => res.json())
    .then(data => appStore.data = data)
}

// this fetches the new data when `appStore.searchString` changes (because `fetchData` is relying on `appStore.searchString`)
// this is basically the same as doing it in `componentDidUpdate` without polluting the view layer
observe(fetchData)

function onChange (ev) {
  appStore.searchString = ev.target.value
}

export default view(() =>
  <input onChange={onChange} value={appStore.searchString} />
  <ul>
    {appStore.data.forEach(item => <li>{JSON.stringify(item)}</li>)}
  </ul>
)
```

- When to user types in the input field the `onChange` handler updates `appStore.searchString`
- `fetchData` is automatically triggered by `observe`
- When the new data arrives `appStore.data` updates which trigger a new UI render.

I wouldn't do this though. Automatic reactions should be used sparingly to keep the flow understandable. I would only use them as the last step of this chain (when you render out data). Triggering automatic data flow on data changes can very quickly become a nightmare to maintain. I would do the above example like this:

```jsx
import React from 'react'
import { view, store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const appStore = store({
  searchString: '',
  data: []
})
```

function fetchData () {
  fetch(`myPage.com?search=${appStore.searchString}`)
    .then(res => res.json())
    .then(data => appStore.data = data)
}

function onChange (ev) {
  appStore.searchString = ev.target.value
  // call fetchData manually, when needed
  fetchData()
}

export default view(() =>
  <input onChange={onChange} value={appStore.searchString} />
  <ul>
    {appStore.data.forEach(item => <li>{JSON.stringify(item)}</li>)}
  </ul>
)
```

**Comment by solkimicreb** [comment]
Hi!

Does this answer your question? I am doing some issue cleanup and I can't decide if I can close this one.

**Comment by AntonioRedondo** [comment]
Hey @solkimicreb, yes, that perfectly answers my question. Thanks!
