### ISSUE TITLE
Wrapping render method of column of rc-table gives error

### ISSUE THREAD

**Issue by lishine** [solkimicreb/react-easy-state#66]
```
import Table from 'rc-table'
import { ordersStore } from 'orders/ordersStore'

const columns = [
	{
		title: 'Download',
		dataIndex: 'download',
		width: 200,
		render: view((value, row, index) => (
			<span>
				<button
					data-tip="download invoice"
					type="button"
					className="svg-btn invoice-btn"
					onClick={() => ordersStore.onInvoiceDownload(index)}>
					{ordersStore.loading === 'invoiceDownload' ? <LoadingPulse /> : <Invoice />}
				</button>
				<button
					data-tip="download pdf"
					type="button"
					className="svg-btn package-btn"
					onClick={() => ordersStore.onPackageDownload(index)}>
					{ordersStore.loading === 'packageDownload' ? <LoadingPulse /> : <Barcode />}
				</button>
				<ReactTooltip type="warning" />
			</span>
		)),
	},
]
export default view(() => {
	return (
		<>
			<Table rowKey="number" columns={columns} data={ordersStore.data} />
		</>
	)
})

```

```
TableCell.js?0d57:72 Uncaught TypeError: Class constructor ReactiveHOC cannot be invoked without 'new'
    at TableCell.render (TableCell.js?0d57:72)
    at finishClassComponent (react-dom.development.js?61bb:13537)
    at updateClassComponent (react-dom.development.js?61bb:13500)
    at beginWork (react-dom.development.js?61bb:14089)
    at performUnitOfWork (react-dom.development.js?61bb:16415)
    at workLoop (react-dom.development.js?61bb:16453)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:145)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:195)
    at invokeGuardedCallback (react-dom.development.js?61bb:248)
    at replayUnitOfWork (react-dom.development.js?61bb:15744)
```

**Comment by solkimicreb** [comment]
I will need a bit more context to solve this.

- What version of easy state are you using?
- Are you using a [special build](https://github.com/solkimicreb/react-easy-state#alternative-builds) or the default one?

Thanks!

**Comment by solkimicreb** [comment]
Updating to the latest version (6.0.5) should solve this issue without any breaking changes for you. It also adds auto batching, which is pretty nice for performance.

Some context: the 5.x versions exposed an ES5 build by default to support older minifiers. The 6.x versions switched to an ES6 default version. ES5 and ES6 class inheritance are incompatible with each other, extending an ES5 class from ES6 code won't work. The rc-table is probably not transpiled and has ES6 classes so the older ES5 version of the lib is not working well with it.

**Comment by lishine** [comment]
Sorry for not mentioning the versions.
I actually updated to 6.0.5 and react 16.6.3.

**Comment by solkimicreb** [comment]
And you still have the issue? Is your project open source/could you share it by any chance?

**Comment by lishine** [comment]
The above issue is with the last versions.
Open source
I am working on the master, currently the view wrapper removed
[https://github.com/lishine/login-full-stack/blob/master/src/client/orders/view/Orders.js](url)

**Comment by solkimicreb** [comment]
Oh, my bad 😄 I missed this part `render: view((value, row, index) => (`. I thought that you only use `view` at the end of the file.

`view` is a wrapper for components, you should not wrap simple functions with it. (A component is a function that is invoked by the react core in this case.) The `render` function is called as a normal function by the `rc-table` package, it should not be wrapped by `view`. Is it not reactive if you do not wrap the `render` by `view` (and wrap the exported table only)?

**Comment by lishine** [comment]
Ok, thanks, understood.
Currently the buttons do not manipulate the data. They initiate file download and then the specific button should show loading indicator.
Actually, you reminds me, in this case I can set the appropriate column data field and the button will react to it.
But what if I the buttons need to react to some common store variable, like setting all of them loading, how do I make the render reactive ?
Currently I set dummy field in the exported function.

**Comment by solkimicreb** [comment]
Using third party none observer components together with observable data is a recurring issue. I will add a related readme section soon.

**Comment by solkimicreb** [comment]
Added a new readme section: https://github.com/solkimicreb/react-easy-state#usage-with-third-party-components. Could you check it when you have a few minutes to spare? Is it understandable/relevant?

**Comment by lishine** [comment]
Ok, I read it.
Deep cloning makes the whole component rerender on each property of the store, which is not performant, I suppose or at least not nice.
Ussing the dummy solution, at least I make the table rerender on it's specific dependendcy, but have to list them all.
No better solutions?
Is this problem common to all state libraries such as redux, mobx or the new react context?

**Comment by solkimicreb** [comment]
> Deep cloning makes the whole component rerender on each property of the store, which is not performant, I suppose or at least not nice.

This is the exact way the table component and vanilla React is supposed to work. Without easy state you would have to do the immutable update (partial cloning) on every state change and the table would re-render on each of them. If the table is nicely implemented internally (and has shouldComponentUpdate checks) it will only update the necessary parts, but you can't do anything from the outside to guarantee this.

> Is this problem common to all state libraries such as redux, mobx or the new react context?

It's not really a problem, it's really just vanilla React behavior. You have to do the same thing with mobx to 'switch between the immutable React and mutable MobX' interface. With redux you don't have to do the deep cloning, but it has the same rendering behavior. (You have to do the immutable update of the data by hand to re-render the Table comp on every change. The table comp is responsible of diffing and optimizing from then on.)

I hope this clarifies it.
