### ISSUE TITLE
websocket batching issue with `this` reference

### ISSUE THREAD

**Issue by NaNdreas** [solkimicreb/react-easy-state#69]
Hi,

I have an issue with react-easy-state v6.0.4 and higher and websocket events from https://www.npmjs.com/package/sfs2x-api, and I'm pretty sure it's the websocket batching that's causing it. 

The problem comes when I'm using the `view` wrapper and an sfs2x-api eventListener for `onConnection`. Internally sfs2x-api relies on a `this` reference, which is undefined if react-easy-state is present. The exact error (in sfs2x-api) is `Cannot read property '_scope' of undefined`. The stacktrace comes from react-easy-state batching (https://github.com/solkimicreb/react-easy-state/blob/master/src/scheduler.js#L88). As soon as I remove the `view` wrapper there's no error. 

Please see this codesandbox I made with v6.0.5 if you want to try it: https://codesandbox.io/s/w20k86yr4k (note that it doesn't matter if connection fails or not, still same error)

It looks like they don't provide the actual source files, but I found a compiled unminified version that looks like the same code, and here is the line of the error if that's of any help:
https://github.com/ohze/sfs2x-js/blob/master/index.js#L4334

Sorry for not being able to pinpoint more exactly what the issue in react-easy-state is (if any), this is as far as I got and I hope someone can help me solve the last pieces. 

Thanks

**Comment by solkimicreb** [comment]
Hi!

This was more than enough to find the issue, thanks. I fixed it, added some additional tests, and published v6.0.6 with it. Please try it when you have some time. Release notes are here: https://github.com/solkimicreb/react-easy-state/releases/tag/v6.0.6

**Comment by NaNdreas** [comment]
Wow, thank you so much for the super fast fix, I just tried it in my project and it works! Thanks
