### ISSUE TITLE
Discourage direct mutation to global store.

### ISSUE THREAD

**Issue by 5achinJani** [solkimicreb/react-easy-state#7]
In the contacts example the `Contact` component mutates the global store directly by doing
```javascript
 Object.assign(this.props.contact, this.store.currentContact)
``` 
I assume it is for demonstration purpose for letting the users know that 'direct mutations' works too and that's great but according to the general practice direct mutation are bad for real life apps and there should be a function for it like you have for `onDelete` . 
```javascript
 store.deleteContact(this.props.contact)
``` 
I just want to suggest that wouldn't it be better to add a warning as comments in the code example or in the main readme saying that 'Though direct mutation to global store from a component works but it's not recommended as a general practice.' 
Anyway nice library. :+1:

**Comment by solkimicreb** [comment]
Hi! I am on holiday this week. I can check this early next week if that works for you. Thanks for the issue.

**Comment by solkimicreb** [comment]
Hi! I am back 🙂  sorry for the late response.

You have a valid point. I will add a warning, but I would rather keep the code as it is now. This is the reason:

The repo is tested through the examples. You can find the code [here](https://github.com/solkimicreb/react-easy-state/tree/master/__tests__). I felt that this has the benefit of having a 'more lifelike' test coverage and ensuring that the examples cover all of the edge cases that Easy State can handle.

Refactoring the code would remove some valuable test coverage, but adding a warning comment is indeed a right step 🙂 I will add one today and close this issue later, if that works for you.

**Comment by 5achinJani** [comment]
All great. :+1: :)

**Comment by solkimicreb** [comment]
Added discouraging comments 🙂
