### ISSUE TITLE
easy-state without React

### ISSUE THREAD

**Issue by kristianmandrup** [solkimicreb/react-easy-state#72]
Hey,

I would love to use easy-state but without havint to use React. How much would it take to extract the proxy state management? Why not provide this as a separate module? Can you recommend any proxy based state managers in npm land?

I feel the time to abandon frameworks such as React, Angular, Vue etc. has finally come. Time for a more lightweight approach, such as lit-html with one or more lightweight state managers. Don't think we need VDom either anymore. Just my 2 cents.

Cheers.

**Comment by kristianmandrup** [comment]
Ah, just found atama: https://github.com/franciscop/atama

Looks like an option.

**Comment by solkimicreb** [comment]
Hi!

easy-state a really thin wrapper around the [observer-util](https://github.com/nx-js/observer-util) library (like mobx and mobx-react). You can implement your own state management solution on top of it pretty easily. Let me know if you need some help.

**Comment by kristianmandrup** [comment]
Cool :) Cheers

**Comment by solkimicreb** [comment]
Super simple vanilla HTML sandbox: https://codesandbox.io/s/2y61kvp5y

**Comment by solkimicreb** [comment]
I am closing this, feel free to re-open if needed 🙂
