### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by jeffreyvanhees** [solkimicreb/react-easy-state#75]
Hi folks,

On a fresh project; when I export a component with `export default view(ScreenName);` I got the exception _Can't find variable: Symbol_. This only occurs in Android (emulator and real device). 

Without the `view()`-method the error is gone. 

Only the following packages are installed:

```"react": "16.6.3",
"react-easy-state": "^6.0.6",
"react-native": "0.58.3",
"react-native-gesture-handler": "^1.0.15",
"react-native-vector-icons": "^6.2.0",
"react-navigation": "^3.0.9"
```

What's wrong?

**Comment by jeffreyvanhees** [comment]
Fixed by installing and configuring JavaScriptCore!

See https://github.com/react-native-community/jsc-android-buildscripts

**Comment by solkimicreb** [comment]
Hi! I know that you solved the issue already, but I have a few questions if you don't mind 🙂(ES6 support is catching up there is a chance that you don't need a custom JSC core). Did you start the new project with Expo?

**Comment by jeffreyvanhees** [comment]
Hi! No, without expo. Pure react-native

**Comment by solkimicreb** [comment]
Then there is a little more wait involved. The next react-native version (v59) will likely include a modern JSC by default (https://github.com/facebook/react-native/issues/19737#issuecomment-454205028).
