### ISSUE TITLE
Remove RN peer dependency

### ISSUE THREAD

**Issue by antoinerousseau** [solkimicreb/react-easy-state#80]
React Native is not needed since this lib also works for React JS (Web), so it shouldn't be listed as a peer dependency.

**Comment by solkimicreb** [comment]
I know that it shows annoying npm warnings but it's there intentionally. I would either remove both react-dom and react-native from peer deps or keep both of them. The issue is that npm does not support OR relations of deps for use cases like this.

**Comment by solkimicreb** [comment]
Basically, the react-native folks get the same annoying behavior the other way around. (They get warnings about missing react-dom).

**Comment by antoinerousseau** [comment]
I think we can remove both then, people need one or the other anyway to have their code work...

**Comment by solkimicreb** [comment]
I am getting back to this, sorry for the long pause

**Comment by solkimicreb** [comment]
I removed react-dom and react-native from the peer dependencies in v6.1.3, it makes more sense this way. Thanks for the issue.
