### ISSUE TITLE
best way to implement reset?

### ISSUE THREAD

**Issue by avierr** [solkimicreb/react-easy-state#83]
what would be the best way to implement reset to original state for the example from the readme:

````
const user = store({ name: 'Rick' })
````

**Comment by Sphinxs** [comment]
You can start your store using a `const` variable, that represents the initial state. If you need to reset the store, you can create a method to get the `const` variable and set it to the store state.

**Comment by solkimicreb** [comment]
I don't usually reset everything on new uses. The possibility of removing some older data and selectively fetching new ones is a benefit of singleton global stores. If you find yourself doing a lot of resets you should probably consider moving some data to local states.

To actually answer your question 🙂 : I usually have an init method on my stores that reset/refetch the part of the props that should be resetted. I don't try to automate this or 'do it in a smarter way'.

**Comment by solkimicreb** [comment]
I hope we answered your question. I am closing this issue for now but feel free to reopen any time.
