### ISSUE TITLE
attempting to change the setter of an unconfigurable prop

### ISSUE THREAD

**Issue by Vibing** [solkimicreb/react-easy-state#84]
I used `react-easy-state`  in my iphone。
I used `react-easy-state/dist/cjs.es5.js`、`react-easy-state/dist/es.es5.js`, but still reported an error:
<img width="1001" alt="WX20190521-144325@2x" src="https://user-images.githubusercontent.com/10387532/58074084-df3c4e80-7bd6-11e9-9117-8f3d53f035f7.png">

- IOS version: 9.3.5
- Browser：Safari

**Comment by solkimicreb** [comment]
Fixed it hopefully, I will publish a new release soon with the fix.

**Comment by Vibing** [comment]
> Fixed it hopefully, I will publish a new release soon with the fix.

I look forward to it

**Comment by solkimicreb** [comment]
I just release a new patch (v6.1.2) which should fix this issues. Please reopen it if the issues is not fixed, thanks!

**Comment by Vibing** [comment]
@solkimicreb Thank you for solving the problem for me.
emm...but it still has a compatibility issue：
<img width="938" alt="WX20190527-164217@2x" src="https://user-images.githubusercontent.com/10387532/58407478-6fc6d300-809e-11e9-9a21-653eddb6b0e8.png">
IOS9.x do not support `Proxy`

**Comment by solkimicreb** [comment]
iOS9 is not supporte, which is something that I can not fix unfortunately 😞 Proxies are not polyfillable and they make up the most essential part of this library. You can find the list of supported platforms [here](https://github.com/solkimicreb/react-easy-state#platform-support).
