### ISSUE TITLE
batchedCallbacks memory leak in Chrome

### ISSUE THREAD

**Issue by AMStrix** [solkimicreb/react-easy-state#85]
First, thanks for an excellent library!

Second, there appears to be a memory leak for batched functions in Chrome.

- os: macOS 10.14.4
- browser: Chrome 74.0.3729.157
- `react-easy-state@6.1.1`
- `react@16.8.6`

I noticed the heap growing linearly in my app as it polls for data from a rest api. I narrowed it down to the batched callbacks mechanism in `scheduler.js` using the chrome devtools/Memory profiler. 

The memory gets released when the `globalObj` batched method assignments are removed from `scheduler.js`. 

#### devtools/Memory/Allocation instrumentation timeline
![Screen Shot 2019-05-21 at 10 56 35 AM](https://user-images.githubusercontent.com/11430954/58113033-57484b80-7bba-11e9-85a0-3867fb0e5312.png)

This behavior is also observable on the [beer finder](https://solkimicreb.github.io/react-easy-state/examples/beer-finder/build/) demo. With the Memory profiler - Allocation instrumentation on timeline running just repeatedly enter queries into the search.

#### beer finder
![Screen Shot 2019-05-21 at 11 26 01 AM](https://user-images.githubusercontent.com/11430954/58113493-3df3cf00-7bbb-11e9-8f99-80d213f41fd7.png)

**Comment by solkimicreb** [comment]
Thanks for all the details! It feels good to see issues like this 🙂 I will look into this in a few hours.

**Comment by solkimicreb** [comment]
This should definitely be a WeakMap: https://github.com/solkimicreb/react-easy-state/blob/master/src/scheduler.js#L18. I will check if I made some other obvious mistakes with the batching. 🤦‍♂

**Comment by solkimicreb** [comment]
I just release a new patch (v6.1.2) which should fix this. Please reopen it if the issue is not fixed. Thanks for the nice detailed issue again 🙂

**Comment by AMStrix** [comment]
Upgraded, works great! Thanks for the quick turnaround on this. 

Much appreciated and happy coding to you!
