### ISSUE TITLE
how to share state between two react-apps

### ISSUE THREAD

**Issue by evnix** [solkimicreb/react-easy-state#86]
I have a global variable like

`window.myStore = store({})`

This works perfectly on one app, but when I use/update the same variable `window.myStore` on different react apps,  either of the one updates/renders but not both.

**Comment by solkimicreb** [comment]
I think you have two separate instances of easy state (one for each app). There should only be a single easy state instance for it to work properly. Let me know if you can't get rid of one of them.

**Comment by evnix** [comment]
I managed to change the code to use two different stores and sync them with pub sub.
So now I can slowly move my redux code to react-easy-state

what would be nice is able to listen to updates(like pub-sub) on a particular key,

so if I update `a.b.c=20` then I can listen to changes like `a.b.c.onUpdate(()=>{ /*do something*/ })`

or even `subscribe(a.b.c, ()=>{ /*do something*/ })`

I am not sure what would be the best way to do this 🤔

**Comment by solkimicreb** [comment]
Easy State is a thin wrapper over the [observer-util](https://github.com/nx-js/observer-util) library which can create general purpose reactions. `view` is a special reaction which renders components on data changes. The below snippet is an example of a more general reaction.

```js
import { store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const a = store({
  b: { c: 12, d: 3, e: 2 }
})

// this runs whenever a.b.c or a.b.d changes but does not run when a.b.e changes (since it is not used in the function)
observe(() => {
  console.log(a.b.c + a.b.d)
})
```

You could do anything in these generic reactions, `console.log` is just a bad example. 

I am strongly suggesting though to only use reactions for 'end-of-the-chain' effects - like rendering and data persisting. Do not mutate data based on other data mutation, but use getters instead.

```js
import { store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const a = store({
  b: { c: 12, d: 3 }
})

const z = store({ q: 12 })

// don't do this
observe(() => {
  z.q = a.b.c + a.b.d
})
```

```js
// do this instead
const a = store({
  b: { c: 12, d: 3 }
})

const z = store({
  get q () {
    return a.b.c + a.b.d
  }
})
```

Another warning: do not try to solve double easy-state instance issues by synchronizing the stores with reactions as it will cause a lot of headaches. If you can't get to a single easy state somewhy letme know.

I hope some of these helps 🙂

**Comment by evnix** [comment]
Ah that's perfect!!
Thanks a lot for the explanation!!!
